# This is a basic workflow to help you get started with Actions

name: Release Versioning

# Triggers the workflow on push
on:
  push:
    branches:
      - development
      - master

jobs:
  version_bump:
    runs-on: ubuntu-latest
    name: Version Bump
    steps:
     # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

     # Run Docker container via GitHub Actions
      - name: Docker Bump Version
        uses: ./.github/actions/
        id: docker_run
        with:
          REPO-TOKEN: ${{ secrets.API_KEY_REPO_BRANCH_TEST }}
          REPO-NAME: ${{github.repository}}