# This is a basic workflow to help you get started with Actions

name: Release Versioning

# Triggers the workflow on push or pull request
on:
  push:
    branches: [ development ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Bump Version
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Bump Version
        run: |
          echo "New Version: ${{ steps.hello.outputs.tag_new }}"

#          git describe --tags $(git rev-list --tags --max-count=1)
#          echo "The time was ${{ steps.hello.outputs.time }}"
#::set-env name={name}::{value}
#echo "::set-output name=action_fruit::strawberry"
#echo "::add-path::/path/to/dir"
